server:
  port: 8080

spring:
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        trace: false
        web-allow-others: true

  datasource:
    url: jdbc:h2:file:./database/db
    driver-class-name: org.h2.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  freemarker:
    template-loader-path: classpath:/templates
    settings:
      number_format: 0.##

  task:
    execution:
      pool:
        core-size: 30

mybatis:
  mapper-locations: classpath:mapping/*.xml

logging:
  level:
    org.springframework: error

pangu:
  synchronizer:
    url: http://plugin.pangu.javamall.com.cn:8082
