server:
  port: 8080

spring:
  h2:
    console:
      enabled: true
      path: /h2

  datasource:
    url: jdbc:h2:file:./db
    driver-class-name: org.h2.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  freemarker:
    template-loader-path: classpath:/templates

mybatis:
  mapper-locations: classpath:mapping/*.xml

logging:
  level:
    org.springframework: error
